config/routes.rb
Rails.application.routes.draw do
  root "pins#index"
  resources :pins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :authenticate_user!, except: [:index]

    def index
        @pins = Pin.all
    end

    def new
        @pin = Pin.new
    end

    def create
        pin = Pin.new(pin_params)
        pin.user = current_user
        if pin.save
            redirect_to root_path
        else
            render :new
        end
    end

    private
        def pin_params
            params.require(:pin).permit(:title, :image_url)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinteresante2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Pinteresante</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <li><%= link_to "Nuevo Pin", new_pin_path %></li>
              <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Registrarse", new_user_registration_path %></li>
              <li><%= link_to "Ingresar", new_user_session_path %></li>
            <% end  %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled clearfix masonry">
    <% @pins.each do |pin| %>
        <div class="pin panel panel-default">
            <div class="panel-body">
                <img src="<%= pin.image_url %>" alt="<%= pin.title %>">
                <h2><%= pin.title %></h2>
                <p class="user">Publicado por <%= pin.user.email %></p>
            </div>
        </div>
    <% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <h1>Nuevo Pin</h1>

            <%= form_for @pin do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: "form-control"%>
                </div>
                <div class="form-group">
                    <%= f.label :image_url %>
                    <%= f.url_field :image_url, class: "form-control"%>
                </div>
                <div class="action">
                    <%= f.submit class: "btn btn-primary btn-lg btn-block"%>
                </div>
            <% end %>
        </div>
    </div>
</div>